server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://8.134.163.127:3306/staff?useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
  application:
    name: staff-service
mybatis:
  type-aliases-package: com.ankang.staff.pojo