server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://192.168.190.130:3306/drugs?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: drugs-service
  cloud:
    nacos:
      server-addr: 192.168.190.130:8848
#      discovery:
#        namespace: 6e0278bd-a021-46dc-9fa7-2aa98a91c1ba
#        ephemeral: false
mybatis:
  type-aliases-package: com.ankang.pojo.drugsService
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ankang: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
