server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.190.130:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: drugs-service
          url: lb://drugs-service
          predicates:
        - id: WareHouseService
          url: lb://warehouseservice
          predicates:
        - id: UserService
          url: lb://userservice
          predicates:
        - id: StaffService
          url: lb://staffservice
          predicates: