server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 47.115.216.208:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: drugs-service
          uri: lb://drugs-service
          predicates:
            - Path=/drugs/**,/drugsType/**,/drugsUnit/**
        - id: wareHouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/warehouse/**,/warehouseStaffRecord/**,/warehouseType/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/purchaseRecord/**,/symptom/**,/userLevelType/**
        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/staff/**,/operator/**,/operatorType/**,/pharmacy/**,/authority/**