server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.190.130:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: drugs-service
          uri: lb://drugs-service
          predicates:
            - Path=/drugs/**
        - id: wareHouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/warehouse/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/staff/**,/operator/**,/operatorType/**,/pharmacy/**,/authority/**