server:
  port: 10010 # 网关端口
spring:
  redis:
    database: 1
    host: 47.115.216.208
    port: 6379
    password: 3302983
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 47.115.216.208:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: drugs-service
          uri: lb://drugs-service
          predicates:
            - Path=/drugs/**,/drugsType/**,/drugsUnit/**
        - id: wareHouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/warehouse/**,/warehouseStaffRecord/**,/warehouseType/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/purchaseRecord/**,/symptom/**,/userLevelType/**,/shopingCar/**
        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/staff/**,/operator/**,/operatorType/**,/pharmacy/**,/authority/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**