server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://47.115.216.208:3306/warehouse?useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
  application:
    name: warehouse-service
mybatis:
  type-aliases-package: com.ankang.warehouse.pojo

