server:
  port: 5006
spring:
  datasource:
    url: jdbc:mysql://8.134.163.127:3306/warehouse?useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
  application:
    name: warehouse-service
mybatis:
  type-aliases-package: com.ankang.warehouse.pojo

