server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.115.216.208:3306/user?useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
  application:
    name: user-service
mybatis:
  type-aliases-package: com.ankang.user.pojo

